dist: trusty
matrix:
  include:
    - language: elm
      node_js: '10'
      elm: '0.19.0'
      services:
        - docker

      before_script:
        - cd webui

      script:
        - docker-compose --version
        - docker-compose build --pull elm
        - docker-compose up --abort-on-container-exit --exit-code-from=elm --force-recreate

    - language: go
      go:
        - '1.12.x'
      env:
        - GO111MODULE=on
      services:
        - docker

      before_script:
        - cd backend
        - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - go mod download

      script:
        - fossa analyze -c ../.fossa.yml
        - scripts/docker-up-test

      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

      after_success:
        - mv dist/coverage.txt coverage.txt
        - bash <(curl -s https://codecov.io/bash)
        - fossa test --timeout 300
