// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Message struct {
	Body string `json:"body"`
}

type User struct {
	GivenName  string `json:"givenName"`
	FamilyName string `json:"familyName"`
	Email      string `json:"email"`
}
