-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Object.User exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.ScalarCodecs
import API.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


givenName : SelectionSet String API.Object.User
givenName =
    Object.selectionForField "String" "givenName" [] Decode.string


familyName : SelectionSet String API.Object.User
familyName =
    Object.selectionForField "String" "familyName" [] Decode.string


email : SelectionSet String API.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string
