version: '2.1'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -dbPath /data/dynamodb-local -sharedDb"
    ports:
      - "8000:8000"
    volumes:
      - ./data/dynamodb-local:/data/dynamodb-local
